#!/usr/bin/python
import os, sys

virtenv = os.environ['APPDIR'] + '/virtenv/'
datadir = os.environ['OPENSHIFT_DATA_DIR']
appname = os.environ['OPENSHIFT_APP_NAME']
os.environ['PYTHON_EGG_CACHE'] = os.path.join(virtenv, 'lib/python2.6/site-packages')
virtualenv = os.path.join(virtenv, 'bin/activate_this.py')
try:
    execfile(virtualenv, dict(__file__=virtualenv))
except IOError:
    pass

os.environ['DJANGO_SETTINGS_MODULE'] = "reviewboard.settings"
os.environ['PYTHON_EGG_CACHE'] = datadir + "/" + appname + "/tmp/egg_cache"
os.environ['HOME'] = datadir + "/" + appname + "/data"

sys.path = [datadir + '/' + appname + '/conf'] + sys.path

import django.core.handlers.wsgi
application = django.core.handlers.wsgi.WSGIHandler()
